---
 apiVersion: apps/v1beta1
 kind: Deployment
 metadata:
   name: redis
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: redis
     spec:
       containers:
         - name: redis
           image: redis
           ports:
             - containerPort: 6379

---
 apiVersion: apps/v1beta1
 kind: Deployment
 metadata:
   name: redis-commander
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: redis-commander
     spec:
       containers:
         - name: redis-commander
           image: rediscommander/redis-commander:latest
           env:
             - name: REDIS_HOSTS
               value: redis
           ports:
             - containerPort: 8081

---
 apiVersion: apps/v1beta1
 kind: Deployment
 metadata:
   name: master
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: master
     spec:
       containers:
         - name: master
           image: yosypmykhailiv/cee-master
           env:
             - name: RUNNERS
               value: "php7.1, php7.2, java8, java12"
             - name: RUNNER_IMAGE
               value: "yosypmykhailiv/cee-runner"
           ports:
             - containerPort: 3000





---
 apiVersion: v1
 kind: Service
 metadata:
   name: redis
 spec:
   selector:
     app: redis
   ports:
     - protocol: TCP
       port: 6379
       targetPort: 6379

---
 apiVersion: v1
 kind: Service
 metadata:
   name: redis-commander
 spec:
   selector:
     app: redis-commander
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 8081
       targetPort: 8081

---
 apiVersion: v1
 kind: Service
 metadata:
   name: master
 spec:
   selector:
     app: master
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000