---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: redis
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: redis
   template:
     metadata:
       labels:
         app: redis
     spec:
       containers:
         - name: redis
           image: redis
           ports:
             - containerPort: 6379

---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: redis-commander
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: redis-commander
   template:
     metadata:
       labels:
         app: redis-commander
     spec:
       containers:
         - name: redis-commander
           image: rediscommander/redis-commander:latest
           env:
             - name: REDIS_HOSTS
               value: redis
           ports:
             - containerPort: 8081

---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: master
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: master
   template:
     metadata:
       labels:
         app: master
     spec:
       containers:
         - name: master
           image: yosypmykhailiv/cee-master
           env:
             - name: RUNNERS
               value: "php7.1, php7.2, java8, java12"
             - name: RUNNER_IMAGE
               value: "yosypmykhailiv/cee-runner"
           ports:
             - containerPort: 3000





---
 apiVersion: v1
 kind: Service
 metadata:
   name: redis
 spec:
   selector:
     app: redis
   ports:
     - protocol: TCP
       port: 6379
       targetPort: 6379

---
 apiVersion: v1
 kind: Service
 metadata:
   name: redis-commander
 spec:
   selector:
     app: redis-commander
   ports:
     - protocol: TCP
       port: 8081
       targetPort: 8081

---
 apiVersion: v1
 kind: Service
 metadata:
   name: master
 spec:
   selector:
     app: master
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 80
       targetPort: 3000




---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-handler
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services"]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-job-handler
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-handler
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
