# Namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: cee



# Service accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: master
  namespace: cee
automountServiceAccountToken: true

---
# The 'runner' service account cannot be renamed or removed since it's used by master when creating jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: cee
automountServiceAccountToken: false

# Role management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: master
  namespace: cee
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "pods"]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: master
  namespace: cee
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: master
subjects:
  - kind: ServiceAccount
    name: master
    namespace: cee



# Deployments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: cee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      serviceAccountName: master
      containers:
        - name: master
          image: yosypmykhailiv/cee-master
          env:
            - name: KUBERNETES_NAMESPACE
              value: "cee"
            - name: RUNNERS
              value: "php7.1, php7.2, java8, java12"
            - name: RUNNER_IMAGE
              value: "yosypmykhailiv/cee-runner"
            - name: EXECUTION_TIME_LIMIT
              value: "60"
            - name: EXECUTION_MEMORY_LIMIT
              value: "67108864"
            - name: EXECUTION_STORAGE_LIMIT
              value: "67108864"
            - name: EXECUTION_CPU_REQUEST
              value: "100m"
            - name: EXECUTION_CPU_LIMIT
              value: "200m"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"



# Services
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cee
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: cee
spec:
  selector:
    app: master
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
