version: '3.4'
services:

  redis:
    image: redis
    container_name: redis
    networks:
      - app-network

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 8081:8081
    networks:
      - app-network

  master:
    build:
      context: ./
      dockerfile: docker/images/master/Dockerfile
    image: y.mykhailiv/cee-master
    container_name: master
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: master
      SERVICE_TAGS: dev
      RUNNERS: php7.1, php7.2, java8, java12
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./master:/app
      - /app/node_modules/
    networks:
      - app-network
    command: nodemon --watch ./ -e js,html index.js

  runner:
    build:
      context: ./
      dockerfile: docker/images/runner/Dockerfile
    image: y.mykhailiv/cee-runner
    container_name: runner
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: runner
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./runner:/app
      - /app/node_modules/
    networks:
      - app-network
    command: nodemon --watch ./ -e js,html index.js

  php7.1-runner:
    build:
      context: ./
      dockerfile: docker/images/runner/php/7.1/Dockerfile
    image: y.mykhailiv/cee-php7.1-runner
    container_name: php7.1-runner
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php7.1-runner
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./runner:/app
      - /app/node_modules/
    networks:
      - app-network
    command: nodemon --watch ./ -e js,html index.js

  php7.2-runner:
    build:
      context: ./
      dockerfile: docker/images/runner/php/7.2/Dockerfile
    image: y.mykhailiv/cee-php7.2-runner
    container_name: php7.2-runner
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php7.2-runner
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./runner:/app
      - /app/node_modules/
    networks:
      - app-network
    command: nodemon --watch ./ -e js,html index.js

  java8-runner:
    build:
      context: ./
      dockerfile: docker/images/runner/java/8/Dockerfile
    image: y.mykhailiv/cee-java8-runner
    container_name: java8-runner
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: java8-runner
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./runner:/app
      - /app/node_modules/
    networks:
      - app-network
    command: nodemon --watch ./ -e js,html index.js

  java12-runner:
    build:
      context: ./
      dockerfile: docker/images/runner/java/12/Dockerfile
    image: y.mykhailiv/cee-java12-runner
    container_name: java12-runner
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: java12-runner
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./runner:/app
      - /app/node_modules/
    networks:
      - app-network
    command: nodemon --watch ./ -e js,html index.js

#Docker Networks
networks:
  app-network:
    driver: bridge